.TH md9781-manager 1 "15 January 2003 (v0.2.1)" md9781-manager
.SH NAME
md9781-manager \- manage files on the MD9781 MP3 player
.SH SYNOPSIS
.B md9781-manager
[\fIOPTION\fR]... \fICOMMAND\fR 
.SH DESCRIPTION
This manual page describes how to use the md9781-manager. 
.SH OPTIONS
.PP
.TP
\fB\-e\fR
use smartmedia card
.TP
\fB\-i\fR
ignore playlist (if you know what you do)
.SH COMMANDS
.PP
.TP
\fB\-l\fR
list files that are on the player
.TP
\fB\-p\fR <file>
put a file to the player
.TP
\fB\-g\fR <file number>
get a file from the player
.TP
\fB\-d\fR <file number>
delete a file from the player
.TP
\fB\-r\fR 
regenerate playlist (if you know what you do)
.PP
.SH AUTHOR
Written by Jesper Zedlitz
.SH "REPORTING BUGS"
Report bugs to <jesper@zedlitz.de>

